import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:genui/genui.dart';
import 'package:genui_gen/genui_gen.dart';
import 'package:genui_gen/testing.dart';
import 'package:intl/date_symbol_data_local.dart';
import 'package:intl/intl.dart';
import 'package:quincena/agent/catalog.dart';
import 'package:quincena/genui_catalog.g.dart';
import 'package:quincena/theme/theme.dart';

import 'fonts.dart';

/// The app's own components, without genui's `Text` added to them.
Iterable<CatalogItem> get ownItems => genUiCatalog.items;

Widget host(Widget child) => MaterialApp(
  theme: quincenaTheme(Brightness.light),
  home: Scaffold(body: SingleChildScrollView(child: child)),
);

void main() {
  setUpAll(() async {
    await loadAppFonts();
    Intl.defaultLocale = 'es_CO';
    await initializeDateFormatting('es');
  });

  test('the catalog published for agents outside the app is current', () {
    // An agent written in Python or a second client in SwiftUI composes
    // against this file, not against the Dart. It is regenerated by the test
    // and compared, so a component that changes without the file changing
    // fails here instead of in somebody else's code.
    final file = File('catalog.json');
    final String current =
        '${genUiCatalogJsonString(quincenaCatalog, title: 'Quincena', description: 'Personal finance answers composed from the account.')}\n';
    if (!file.existsSync() || Platform.environment['UPDATE_CATALOG'] == '1') {
      file.writeAsStringSync(current);
    }
    expect(
      file.readAsStringSync(),
      current,
      reason:
          'Regenerate with UPDATE_CATALOG=1 flutter test test/catalog_test.dart',
    );
  });

  testWidgets('nothing the schema allows breaks a component', (tester) async {
    // The fuzzer brings its own app and plain Material theme, which is the
    // point: a component has to survive being drawn somewhere new.
    final List<GenUiFuzzFinding> findings = await genUiFuzz(
      catalog: genUiCatalog,
      pump: tester.pumpWidget,
    );
    expect(findings, isEmpty, reason: genUiFuzzSummary(findings));
  });

  testWidgets('every component tells a screen reader what it is', (
    tester,
  ) async {
    final recorded = <String, List<GenUiSemanticNode>>{};
    for (final CatalogItem item in ownItems) {
      final SemanticsHandle handle = tester.ensureSemantics();
      await tester.pumpWidget(
        host(GenUiExampleSurface(catalog: quincenaCatalog, item: item)),
      );
      await tester.pumpAndSettle();
      recorded[item.name] = genUiRenderedSemantics();
      handle.dispose();
    }

    final List<GenUiAuditFinding> findings = genUiSemanticsAudit(
      recorded,
      // Layout components announce their children, not themselves.
      allowEmpty: const <String>{'Answer', 'Tiles', 'Suggestions'},
    );
    expect(findings.map((GenUiAuditFinding f) => '$f'), isEmpty);
  });
}
